public enum State {
  /**
   * MESI
   */
  MESI_MODIFIED, MESI_EXCLUSIVE, MESI_SHARED, MESI_INVALID,

  /**
   * Dragon
   */
  DRAGON_EXCLUSIVE, DRAGON_SHARED_CLEAN, DRAGON_SHARED_MODIFIED, DRAGON_MODIFY,
}
